export const ORDERS_FETCH_START = 'ORDERS_FETCH_START';
export const ORDERS_FETCH_SUCCESS = 'ORDERS_FETCH_SUCCESS';
export const ORDERS_FETCH_FAILED = 'ORDERS_FETCH_FAILED';

export const REPORTS_FETCH_START = 'REPORTS_FETCH_START';
export const REPORTS_FETCH_SUCCESS = 'REPORTS_FETCH_SUCCESS';
export const REPORTS_FETCH_FAILED = 'REPORTS_FETCH_FAILED';
export const REPORTS_RESET = 'REPORTS_RESET';