/** SALE ORDERS */
export const ORDERS_FETCH_START = 'ORDERS_FETCH_START';
export const ORDERS_FETCH_SUCCESS = 'ORDERS_FETCH_SUCCESS';
export const ORDERS_FETCH_FAILED = 'ORDERS_FETCH_FAILED';

/** REPORTS */
export const REPORTS_FETCH_START = 'REPORTS_FETCH_START';
export const REPORTS_FETCH_SUCCESS = 'REPORTS_FETCH_SUCCESS';
export const REPORTS_FETCH_FAILED = 'REPORTS_FETCH_FAILED';

/** GRID */
export const GRID_RESET = 'GRID_RESET';
export const GRID_SELECTED_START = 'GRID_SELECTED_START';
export const GRID_SELECTED_SUCCESS = 'GRID_SELECTED_SUCCESS';
export const GRID_SELECTED_FAILED = 'GRID_SELECTED_FAILED';
